name: Update NHK News

on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours
  workflow_dispatch: # Allow manual trigger

jobs:
  fetch-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch NHK RSS and convert to JSON
        run: |
          curl -s "https://www3.nhk.or.jp/news/easy/rss/easy-news.xml" \
          | xmllint --format - \
          | awk '/<item>/,/<\/item>/' \
          | head -n 30 > temp.xml

          # Extract titles and links
          titles=$(grep -oPm1 "(?<=<title>)[^<]+" temp.xml | sed '1d')
          links=$(grep -oPm1 "(?<=<link>)[^<]+" temp.xml | sed '1d')

          echo '{ "items": [' > data/news.json
          paste <(echo "$titles") <(echo "$links") | \
          awk '{printf "{\"title\":\"%s\",\"link\":\"%s\"},",$1,$2}' >> data/news.json
          sed -i '$ s/,$//' data/news.json
          echo ']}' >> data/news.json

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/news.json
          git commit -m "Update NHK news"
          git push
