name: Update NHK Easy News

on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours
  workflow_dispatch: # Allows manual trigger

jobs:
  fetch-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install XML tools
        run: sudo apt-get install -y libxml2-utils jq

      - name: Fetch NHK RSS and convert to JSON
        run: |
          mkdir -p data

          # Download RSS feed
          curl -s "https://www3.nhk.or.jp/news/easy/rss/easy-news.xml" -o rss.xml

          # Parse XML for <item> elements and extract titles & links
          # Limit to first 5 items
          titles=($(xmllint --xpath "//item/title/text()" rss.xml | head -n 5))
          links=($(xmllint --xpath "//item/link/text()" rss.xml | head -n 5))

          # Build JSON
          echo '{ "items": [' > data/news.json
          for i in "${!titles[@]}"; do
            title="${titles[$i]}"
            link="${links[$i]}"
            # Escape quotes in title
            title=$(echo "$title" | sed 's/"/\\"/g')
            echo "{\"title\": \"$title\", \"link\": \"$link\"}," >> data/news.json
          done

          # Remove last comma and close JSON
          sed -i '$ s/,$//' data/news.json
          echo ']}' >> data/news.json

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/news.json
          git commit -m "Update NHK news" || echo "No changes to commit"
          git push
