name: Update NHK Easy News

on:
  schedule:
    - cron: '0 */6 * * *' # ✅ Runs every 6 hours
  workflow_dispatch: # ✅ Allows manual run

permissions:
  contents: write  # ✅ Required for committing changes

jobs:
  fetch-news:
    runs-on: ubuntu-latest

    steps:
      # ✅ 1. Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # We'll provide token for push
          fetch-depth: 0

      # ✅ 2. Install tools (for XML parsing)
      - name: Install XML utilities
        run: sudo apt-get install -y libxml2-utils

      # ✅ 3. Fetch NHK RSS and build JSON
      - name: Fetch NHK RSS and convert to JSON
        run: |
          mkdir -p data

          echo "📥 Fetching NHK Easy News RSS..."
          curl -s "https://www3.nhk.or.jp/news/easy/rss/easy-news.xml" -o rss.xml

          # ✅ Use XPath ignoring namespaces
          mapfile -t titles < <(xmllint --xpath "//*[local-name()='item']/*[local-name()='title']/text()" rss.xml | head -n 5)
          mapfile -t links < <(xmllint --xpath "//*[local-name()='item']/*[local-name()='link']/text()" rss.xml | head -n 5)

          echo "✅ Found ${#titles[@]} headlines"
          if [ ${#titles[@]} -eq 0 ]; then
            echo "❌ No headlines parsed. Exiting."
            exit 1
          fi

          # ✅ Build JSON
          echo '{ "items": [' > data/news.json
          for i in "${!titles[@]}"; do
            title="${titles[$i]}"
            link="${links[$i]}"
            title=$(echo "$title" | sed 's/"/\\"/g') # Escape quotes
            echo "{\"title\": \"$title\", \"link\": \"$link\"}," >> data/news.json
          done
          sed -i '$ s/,$//' data/news.json
          echo ']}' >> data/news.json

          echo "✅ news.json updated with top ${#titles[@]} headlines"
          cat data/news.json

      # ✅ 4. Commit and push if changes exist
      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/news.json

          if git diff --cached --quiet; then
            echo "ℹ️ No changes to commit"
          else
            echo "📤 Committing and pushing changes..."
            git commit -m "Update NHK news"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
          fi
