name: Update NHK Easy News

on:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install XML utilities
        run: sudo apt-get install -y libxml2-utils

      - name: Fetch NHK RSS and convert to JSON
        run: |
          mkdir -p data
          echo "📥 Fetching NHK Easy News RSS..."
          curl -s "https://www3.nhk.or.jp/news/easy/rss/easy-news.xml" -o rss.xml

          echo "✅ RSS downloaded. Extracting headlines..."
          raw_titles=$(xmllint --xpath "//*[local-name()='item']/*[local-name()='title']/text()" rss.xml || true)
          raw_links=$(xmllint --xpath "//*[local-name()='item']/*[local-name()='link']/text()" rss.xml || true)

          if [ -z "$raw_titles" ] || [ -z "$raw_links" ]; then
            echo "❌ Failed to extract titles or links from RSS"
            exit 1
          fi

          titles=$(echo "$raw_titles" | tr ' ' '\n')
          links=$(echo "$raw_links" | tr ' ' '\n')

          echo '{ "items": [' > data/news.json
          i=0
          while read -r title && read -r link <&3; do
            title=$(echo "$title" | sed 's/"/\\"/g')
            echo "{\"title\": \"$title\", \"link\": \"$link\"}," >> data/news.json
            i=$((i+1))
            if [ $i -ge 5 ]; then break; fi
          done <<< "$titles" 3<<< "$links"

          sed -i '$ s/,$//' data/news.json
          echo ']}' >> data/news.json

          echo "✅ news.json updated with $i headlines:"
          cat data/news.json

      - name: Commit and Push changes
        env:
          GIT_PUSH_URL: https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/news.json
          if git diff --cached --quiet; then
            echo "ℹ️ No changes to commit"
          else
            echo "📤 Committing and pushing changes..."
            git commit -m "Update NHK news"
            git push "$GIT_PUSH_URL" HEAD:main
          fi
