name: Update NHK Easy News

on:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours
  workflow_dispatch:

permissions:
  contents: write  # ✅ Give the workflow permission to push changes

jobs:
  fetch-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # We'll use token for push
          fetch-depth: 0             # Ensure full history for commit

      - name: Install XML tools
        run: sudo apt-get install -y libxml2-utils jq

      - name: Fetch NHK RSS and convert to JSON
        run: |
          mkdir -p data

          # Download RSS feed
          curl -s "https://www3.nhk.or.jp/news/easy/rss/easy-news.xml" -o rss.xml

          # Extract titles and links (first 5)
titles=($(xmllint --xpath "//*[local-name()='item']/*[local-name()='title']/text()" rss.xml | head -n 5))
links=($(xmllint --xpath "//*[local-name()='item']/*[local-name()='link']/text()" rss.xml | head -n 5))

          # Build JSON
          echo '{ "items": [' > data/news.json
          for i in "${!titles[@]}"; do
            title="${titles[$i]}"
            link="${links[$i]}"
            title=$(echo "$title" | sed 's/"/\\"/g')
            echo "{\"title\": \"$title\", \"link\": \"$link\"}," >> data/news.json
          done
          sed -i '$ s/,$//' data/news.json
          echo ']}' >> data/news.json

          echo "Updated news.json with ${#titles[@]} items"

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/news.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update NHK news"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
          fi
